name: "Invitation"

description: "Automate Invites"

inputs:
  OWNER:
    description: "repo owner"
    required: true
    default: "codinasion"

  REPO:
    description: "repo name"
    required: true
    default: ".github"

  TOKEN:
    description: "github token"
    required: true

  ADD_ALL_TO_TEAM:
    description: "add all members to team"
    required: true
    default: false
  
  INVITE_USER:
    description: "invite user to organization"
    required: true
    default: false
  
  USERNAME:
    description: "username to invite"
    required: true
    default: "harshraj8843"
  
  ISSUE_NUMBER:
    description: "issue number"
    required: true
    default: 1

runs:
  using: "node16"
  main: "../action.js"
